# -*- coding: utf-8 -*-
"""name.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaNFueE9iEVd36JtEsJb-ZgRMalKLXYa
"""

name = ["Kagetera","John","Peter","Alex","Claude"]
name.append ("Ziada")
name.append ("UoK")
name.append ("Nirere")
name.sort
print (name)